### ISSUE TITLE
Measure Radius

### ISSUE THREAD

**Issue by AbhinavMadahar** [AbhinavMadahar/Amish-Tech-Support#17]
## Measure the radius of the following wheels in cm

* Front wheels
* Back wheel (smaller)

#### Comment the data, specifying it's in centimetres

That way I can be sure there was no miscommunication. After all, the Mars Climate Orbiter crashed into Mars because Lockheed-Martin used English Units without telling NASA, which used metric. $193 million was lost.

**Comment by brent34** [comment]
large wheel radius is 2.75 centimeters

small wheel radius is 1.25 centimeters
