### ISSUE TITLE
Measure Distances

### ISSUE THREAD

**Issue by AbhinavMadahar** [AbhinavMadahar/Amish-Tech-Support#3]
# Measure the following distances in centimetres:
![untitled drawing 1](https://cloud.githubusercontent.com/assets/8312336/6074445/82ab2ee2-ad8c-11e4-9671-48ca732742ec.png)

1. aisle gap
2. desk gap
3. desk
4. startbox gap
5. startbox
6. robot from front wheel to back wheel

## Write the distances in the comments below

**Comment by AbhinavMadahar** [comment]
@brent34 you have to measure it again- I lost the measurements. And make sure to write down what the measurements are in the comments this time.

**Comment by brent34** [comment]
startbox- 30cm
robot from from to back wheel- 12cm
start box gap- 14cm
desk- 36cm
desk gap- 7cm
aisle gap- 40cm
